sudo: required
language: node_js
node_js:
  - "lts/*"
services:
  - docker
notifications:
  email:
    - ${NOTIFICATIONS_EMAIL}
stages:
  - test
  - publish
jobs:
  include:
    - stage: test
      script:
        - npm test
    - stage: publish
      script:
        - npm run build
        - docker login -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_PASSWORD}
        - git checkout ${TRAVIS_BRANCH};
        - COMMIT_MESSAGE=$(git log -n 1 --pretty=format:"%B");
        - |
          if [[ $COMMIT_MESSAGE == *"[force build]"* ]]; then
            ./provisioning/versioning/iterate minor -i -q;
          else
            ./provisioning/versioning/iterate -i -q;
          fi;
        - ./provisioning/versioning/iterate -q
        - git push -q https://zephinzer:${GITHUB_TOKEN}@github.com/zephinzer/janus.git --tags;
        - docker push ${DOCKERHUB_REPO_URL}:$(./provisioning/versioning/get-latest -q)
        - docker push ${DOCKERHUB_REPO_URL}:latest
        - docker logout
