module.exports = {
  ERROR: {
    SUCCESS: 'OK',
    UNSUPPORTED_SOURCE: 'SOURCE_NOT_SUPPORTED',
    UNSUPPORTED_TYPE: 'TYPE_NOT_SUPPORTED',
    INVALID_TYPE: 'TYPE_INVALID',
    PERCENTAGE_MISMATCH: 'PERCENTAGE_VALUES_NOT_EQUAL_100',
  },
  LABEL_VALIDATOR: /^[a-zA-Z]*[a-zA-Z0-9\_\-\.]*[a-zA-Z0-9]+$/,
};
